### ISSUE TITLE
Query#getResultSet()#getKBObject() seems pretty slow

### ISSUE THREAD

**Issue by cyc-dev** [cycorp/api-suite#2]
Reported on [Cyc Dev Center > Core API Usages](http://dev.cyc.com/cyc-api/samples/combined.html#comment-1877144415):

> results.getKBObject seems pretty slow. I am trying to get all the results from a query into my own data structure. Is there some way this could be done faster? If I use the toString method on the result set it is very fast, and I could then parse the string, but the string cuts off with only some of the answers.

**Comment by cyc-api-devs** [comment]
[Comment](https://disqus.com/home/discussion/cycdev/cyc_java_api_cyc_java_api_26/#comment-1878099954):

> getKBObject tries to cast the query results into an appropriate subclass of KBObject. So it is slower. We will release a more optimized version soon.
> 
> We would strongly recommended against using string representations of KBObjects in code written with the new APIs. This leads to using string concatenation of concepts to build queries and assertions, which do not scale well for complicated sentences. The string usage should be limited to concept lookup operations only.

**Comment by vijayatcyc** [comment]
We have improved the performance of building KB Objects. But note that, for a extremely large query, it will still take more time, than just string serialization. The changes will be available with 1.0.0-rc3 of the KB API.

**Comment by nwinant** [comment]
This issue was moved to cycorp/cyc-issues#2

**Comment by cyc-dev** [comment]
This issue was moved to cycorp/cyc-issues#2
