### ISSUE TITLE
run-cyc.bat fails with Java 1.8

### ISSUE THREAD

**Issue by jgregoric** [cycorp/api-suite#6]
Running on Windows 7, 64 bit:

C:\OpenCyc\opencyc-4.0\scripts>run-cyc
PORT_OFFSET = 00
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Unrecognized VM option 'UseSpinning'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by davidaschneider** [comment]
What happens when you remove the UseSpinning option from the Java options?

**Comment by cyc-dev** [comment]
You can remove UseSpinning. Some versions of Cyc have launch scripts which
specify VM options no longer supported by Java 8:

http://dev.cyc.com/admin/faq/index.html#usespinning


On Thu, Feb 18, 2016 at 8:21 AM, Dave Schneider <notifications@github.com>
wrote:

> What happens when you remove the UseSpinning option from the Java options?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cycorp/api-suite/issues/6#issuecomment-185743222>.
>



-- 
*Nathan Winant*
*Cycorp, Inc.*
Phone: 512-342-4024
Email: nathan@cyc.com
Web: http://www.cyc.com

**Comment by jgregoric** [comment]
Excellent, thank you for the quick turn-around Nathan.
Regards,
Jim

**Comment by cyc-dev** [comment]
This issue was moved to cycorp/cyc-issues#6
